-- liquibase formatted sql
-- changeset nnvi:alter_table_JOURNEY_add_relations

ALTER TABLE JOURNEY ADD COLUMN country_id BIGINT;
ALTER TABLE JOURNEY ADD COLUMN place_id BIGINT;
ALTER TABLE JOURNEY ADD COLUMN currency_id BIGINT;
ALTER TABLE JOURNEY ADD COLUMN duration_day INTEGER;
ALTER TABLE JOURNEY ADD COLUMN duration_night INTEGER;
ALTER TABLE JOURNEY ADD COLUMN version INTEGER NOT NULL;

ALTER TABLE JOURNEY ALTER COLUMN description SET NOT NULL;
ALTER TABLE JOURNEY ALTER COLUMN status SET NOT NULL;
ALTER TABLE JOURNEY ALTER COLUMN start_date TYPE DATE;
ALTER TABLE JOURNEY ALTER COLUMN end_date TYPE DATE;
ALTER TABLE JOURNEY ALTER COLUMN start_date SET NOT NULL;
ALTER TABLE JOURNEY ALTER COLUMN country_id SET NOT NULL;

ALTER TABLE JOURNEY ADD CONSTRAINT fk_journey_country FOREIGN KEY (country_id) REFERENCES COUNTRY(id);
ALTER TABLE JOURNEY ADD CONSTRAINT fk_journey_place FOREIGN KEY (place_id) REFERENCES PLACE(id);
ALTER TABLE JOURNEY ADD CONSTRAINT fk_journey_currency FOREIGN KEY (currency_id) REFERENCES CURRENCY(id);

-- rollback ALTER TABLE JOURNEY DROP CONSTRAINT fk_journey_currency;
-- rollback ALTER TABLE JOURNEY DROP CONSTRAINT fk_journey_place;
-- rollback ALTER TABLE JOURNEY DROP CONSTRAINT fk_journey_country;
-- rollback ALTER TABLE JOURNEY DROP COLUMN country_id;
-- rollback ALTER TABLE JOURNEY DROP COLUMN place_id;
-- rollback ALTER TABLE JOURNEY DROP COLUMN currency_id;
-- rollback ALTER TABLE JOURNEY DROP COLUMN duration_day;
-- rollback ALTER TABLE JOURNEY DROP COLUMN duration_night;
-- rollback ALTER TABLE JOURNEY DROP COLUMN version;
